SET LOCAL search_path TO oxide_batch, pg_catalog;

DO $$
BEGIN
    IF (SELECT version FROM ob_schema_version WHERE singleton) <> 1 THEN
        RAISE EXCEPTION 'oxide_batch schema version 1 is required before schema 2';
    END IF;
END
$$;

ALTER TABLE ob_step_execution
    ADD COLUMN step_logical_id varchar(128) COLLATE "C",
    ADD COLUMN read_retry_count bigint NOT NULL DEFAULT 0
        CHECK (read_retry_count >= 0),
    ADD COLUMN process_retry_count bigint NOT NULL DEFAULT 0
        CHECK (process_retry_count >= 0),
    ADD COLUMN write_retry_count bigint NOT NULL DEFAULT 0
        CHECK (write_retry_count >= 0),
    ADD COLUMN read_skip_count bigint NOT NULL DEFAULT 0
        CHECK (read_skip_count >= 0),
    ADD COLUMN process_skip_count bigint NOT NULL DEFAULT 0
        CHECK (process_skip_count >= 0),
    ADD COLUMN write_skip_count bigint NOT NULL DEFAULT 0
        CHECK (write_skip_count >= 0),
    ADD COLUMN no_rollback_count bigint NOT NULL DEFAULT 0
        CHECK (no_rollback_count >= 0),
    ADD COLUMN fault_state_format smallint NOT NULL DEFAULT 1
        CHECK (fault_state_format > 0),
    ADD COLUMN fault_state_schema varchar(128) COLLATE "C" NOT NULL
        DEFAULT 'oxide-batch.fault-state'
        CHECK (octet_length(fault_state_schema) BETWEEN 1 AND 128),
    ADD COLUMN fault_state_schema_version integer NOT NULL DEFAULT 1
        CHECK (fault_state_schema_version > 0),
    ADD COLUMN fault_state_payload jsonb NOT NULL
        DEFAULT '{"checkpoint": "0000000000000000000000000000000000000000000000000000000000000000", "entries": []}'::jsonb
        CHECK (jsonb_typeof(fault_state_payload) = 'object')
        CHECK (pg_column_size(fault_state_payload) <= 65536),
    ADD COLUMN fault_state_checksum bytea NOT NULL
        DEFAULT decode(
            'a491114819e0d3bd8b7ca004dc0636f95b45e2fcb1a67ddb5726beaea12f9922',
            'hex'
        )
        CHECK (octet_length(fault_state_checksum) = 32);

UPDATE ob_step_execution SET step_logical_id = step_name
    WHERE step_logical_id IS NULL;

ALTER TABLE ob_step_execution
    ALTER COLUMN step_logical_id SET NOT NULL,
    ADD CONSTRAINT ob_step_execution_logical_id_bounds
        CHECK (octet_length(step_logical_id) BETWEEN 1 AND 128),
    ADD CONSTRAINT ob_step_execution_logical_id_unique
        UNIQUE (job_execution_id, step_logical_id);

CREATE INDEX ob_step_execution_logical_history
    ON ob_step_execution (step_logical_id, job_execution_id, id DESC);

-- Schema 1 declared the category list as an unnamed column check. The
-- generated name is dropped by definition rather than by assumed spelling so
-- the replacement list is the only remaining category constraint.
DO $$
DECLARE
    target regclass;
    generated text;
BEGIN
    FOREACH target IN ARRAY ARRAY[
        'oxide_batch.ob_job_execution'::regclass,
        'oxide_batch.ob_step_execution'::regclass
    ] LOOP
        FOR generated IN
            SELECT conname FROM pg_catalog.pg_constraint
            WHERE conrelid = target
              AND contype = 'c'
              AND pg_get_constraintdef(oid) LIKE '%INVALID_DEFINITION%'
        LOOP
            EXECUTE format(
                'ALTER TABLE %s DROP CONSTRAINT %I', target::text, generated
            );
        END LOOP;
    END LOOP;
END
$$;

ALTER TABLE ob_job_execution
    ADD CONSTRAINT ob_job_execution_failure_category_check
        CHECK (failure_category IN (
            'INVALID_DEFINITION', 'DUPLICATE_EXECUTION', 'ILLEGAL_TRANSITION',
            'TRANSIENT_INFRASTRUCTURE', 'PERMANENT_INFRASTRUCTURE',
            'USER_COMPONENT', 'CANCELLED', 'SERIALIZATION', 'INVARIANT',
            'OPTIMISTIC_CONFLICT', 'TIMEOUT', 'UNSUPPORTED_CAPABILITY',
            'UNKNOWN_COMMIT'
        ));

ALTER TABLE ob_step_execution
    ADD CONSTRAINT ob_step_execution_failure_category_check
        CHECK (failure_category IN (
            'INVALID_DEFINITION', 'DUPLICATE_EXECUTION', 'ILLEGAL_TRANSITION',
            'TRANSIENT_INFRASTRUCTURE', 'PERMANENT_INFRASTRUCTURE',
            'USER_COMPONENT', 'CANCELLED', 'SERIALIZATION', 'INVARIANT',
            'OPTIMISTIC_CONFLICT', 'TIMEOUT', 'UNSUPPORTED_CAPABILITY',
            'UNKNOWN_COMMIT'
        ));

CREATE TABLE ob_flow_decision (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY CHECK (id > 0),
    job_execution_id bigint NOT NULL
        REFERENCES ob_job_execution (id) ON DELETE RESTRICT,
    source_step_execution_id bigint
        REFERENCES ob_step_execution (id) ON DELETE RESTRICT,
    reused_decision_id bigint
        REFERENCES ob_flow_decision (id) ON DELETE RESTRICT,
    sequence bigint NOT NULL CHECK (sequence > 0),
    source_node_id varchar(128) COLLATE "C" NOT NULL
        CHECK (octet_length(source_node_id) BETWEEN 1 AND 128),
    observed_outcome varchar(64) COLLATE "C" NOT NULL
        CHECK (octet_length(observed_outcome) BETWEEN 1 AND 64),
    target_node_id varchar(128) COLLATE "C"
        CHECK (octet_length(target_node_id) BETWEEN 1 AND 128),
    transition_kind varchar(32) COLLATE "C" NOT NULL
        CHECK (transition_kind IN (
            'STEP_EXIT', 'DECIDER', 'COMPLETED_STEP_REUSE'
        )),
    terminal_kind varchar(16) COLLATE "C"
        CHECK (terminal_kind IN ('COMPLETE', 'FAIL', 'STOP')),
    plan_fingerprint bytea NOT NULL CHECK (octet_length(plan_fingerprint) = 32),
    input_digest bytea NOT NULL CHECK (octet_length(input_digest) = 32),
    decided_at timestamptz NOT NULL,
    CONSTRAINT ob_flow_decision_sequence_unique
        UNIQUE (job_execution_id, sequence),
    CONSTRAINT ob_flow_decision_source_unique
        UNIQUE (job_execution_id, source_node_id),
    CONSTRAINT ob_flow_decision_target_shape
        CHECK (
            (target_node_id IS NOT NULL AND terminal_kind IS NULL)
            OR (target_node_id IS NULL AND terminal_kind IS NOT NULL)
        )
);

UPDATE ob_schema_version
    SET version = 2, installed_at = CURRENT_TIMESTAMP
    WHERE singleton;
