SET LOCAL search_path TO oxide_batch, pg_catalog;

DO $$
BEGIN
    IF (SELECT version FROM ob_schema_version WHERE singleton) <> 2 THEN
        RAISE EXCEPTION 'oxide_batch schema version 2 is required before schema 3';
    END IF;
END
$$;

ALTER TABLE ob_job_execution
    ADD COLUMN owner_token bytea
        CHECK (octet_length(owner_token) = 16),
    ADD COLUMN stop_requested_at timestamptz,
    ADD COLUMN stop_requested_by varchar(128) COLLATE "C"
        CHECK (octet_length(stop_requested_by) BETWEEN 1 AND 128),
    ADD CONSTRAINT ob_job_execution_stop_request_shape
        CHECK (
            (stop_requested_at IS NULL AND stop_requested_by IS NULL)
            OR (stop_requested_at IS NOT NULL AND stop_requested_by IS NOT NULL)
        );

ALTER TABLE ob_job_instance
    ADD COLUMN hold_actor varchar(128) COLLATE "C"
        CHECK (octet_length(hold_actor) BETWEEN 1 AND 128),
    ADD COLUMN hold_reason varchar(64) COLLATE "C"
        CHECK (octet_length(hold_reason) BETWEEN 1 AND 64),
    ADD COLUMN hold_placed_at timestamptz,
    ADD CONSTRAINT ob_job_instance_hold_shape
        CHECK (
            (hold_actor IS NULL AND hold_reason IS NULL AND hold_placed_at IS NULL)
            OR (
                hold_actor IS NOT NULL
                AND hold_reason IS NOT NULL
                AND hold_placed_at IS NOT NULL
            )
        );

ALTER TABLE ob_job_execution
    DROP CONSTRAINT ob_job_execution_failure_category_check;

ALTER TABLE ob_job_execution
    ADD CONSTRAINT ob_job_execution_failure_category_check
        CHECK (failure_category IN (
            'INVALID_DEFINITION', 'DUPLICATE_EXECUTION', 'ILLEGAL_TRANSITION',
            'TRANSIENT_INFRASTRUCTURE', 'PERMANENT_INFRASTRUCTURE',
            'USER_COMPONENT', 'CANCELLED', 'SERIALIZATION', 'INVARIANT',
            'OPTIMISTIC_CONFLICT', 'TIMEOUT', 'UNSUPPORTED_CAPABILITY',
            'UNKNOWN_COMMIT', 'SHUTDOWN_INCOMPLETE', 'STALE_RECOVERED'
        ));

ALTER TABLE ob_step_execution
    DROP CONSTRAINT ob_step_execution_failure_category_check;

ALTER TABLE ob_step_execution
    ADD CONSTRAINT ob_step_execution_failure_category_check
        CHECK (failure_category IN (
            'INVALID_DEFINITION', 'DUPLICATE_EXECUTION', 'ILLEGAL_TRANSITION',
            'TRANSIENT_INFRASTRUCTURE', 'PERMANENT_INFRASTRUCTURE',
            'USER_COMPONENT', 'CANCELLED', 'SERIALIZATION', 'INVARIANT',
            'OPTIMISTIC_CONFLICT', 'TIMEOUT', 'UNSUPPORTED_CAPABILITY',
            'UNKNOWN_COMMIT', 'SHUTDOWN_INCOMPLETE', 'STALE_RECOVERED'
        ));

CREATE TABLE ob_operator_request (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY CHECK (id > 0),
    job_instance_id bigint
        REFERENCES ob_job_instance (id) ON DELETE RESTRICT,
    job_execution_id bigint
        REFERENCES ob_job_execution (id) ON DELETE RESTRICT,
    action varchar(16) COLLATE "C" NOT NULL
        CHECK (action IN ('LAUNCH', 'RESTART', 'STOP', 'ABANDON', 'RECOVER')),
    authorization_class varchar(16) COLLATE "C" NOT NULL
        CHECK (authorization_class IN ('READ', 'LIFECYCLE', 'DESTRUCTIVE')),
    operation_id varchar(64) COLLATE "C" NOT NULL
        CHECK (octet_length(operation_id) BETWEEN 1 AND 64),
    actor_ref varchar(128) COLLATE "C" NOT NULL
        CHECK (octet_length(actor_ref) BETWEEN 1 AND 128),
    reason_code varchar(64) COLLATE "C"
        CHECK (octet_length(reason_code) BETWEEN 1 AND 64),
    request_digest bytea NOT NULL CHECK (octet_length(request_digest) = 32),
    observed_version bigint CHECK (observed_version >= 0),
    prior_status varchar(16) COLLATE "C"
        CHECK (prior_status IN (
            'STARTING', 'STARTED', 'STOPPING', 'STOPPED', 'FAILED',
            'COMPLETED', 'ABANDONED', 'UNKNOWN'
        )),
    result_status varchar(16) COLLATE "C"
        CHECK (result_status IN (
            'STARTING', 'STARTED', 'STOPPING', 'STOPPED', 'FAILED',
            'COMPLETED', 'ABANDONED', 'UNKNOWN'
        )),
    outcome_class varchar(16) COLLATE "C" NOT NULL
        CHECK (outcome_class IN ('APPLIED', 'REJECTED')),
    rejection_code varchar(32) COLLATE "C"
        CHECK (rejection_code IN (
            'OPTIMISTIC_CONFLICT', 'INVALID_STATE', 'INSTANCE_COMPLETED',
            'INSTANCE_ABANDONED', 'EXECUTION_ALREADY_ACTIVE',
            'INCOMPATIBLE_DEFINITION', 'RESTART_WITHOUT_PRIOR_ATTEMPT',
            'START_LIMIT_EXCEEDED', 'UNRESOLVED_RECOVERY_REQUIRED',
            'EXECUTION_NOT_FOUND', 'INSTANCE_NOT_FOUND'
        )),
    requested_at timestamptz NOT NULL,
    CONSTRAINT ob_operator_request_identity_unique
        UNIQUE (action, operation_id),
    CONSTRAINT ob_operator_request_outcome_shape
        CHECK (
            (outcome_class = 'APPLIED' AND rejection_code IS NULL)
            OR (outcome_class = 'REJECTED' AND rejection_code IS NOT NULL)
        )
);

CREATE INDEX ob_operator_request_execution
    ON ob_operator_request (job_execution_id, id);

CREATE TABLE ob_retention_action (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY CHECK (id > 0),
    job_instance_id bigint
        REFERENCES ob_job_instance (id) ON DELETE RESTRICT,
    action varchar(16) COLLATE "C" NOT NULL
        CHECK (action IN ('HOLD', 'RELEASE_HOLD', 'APPLY_PURGE')),
    operation_id varchar(64) COLLATE "C" NOT NULL
        CHECK (octet_length(operation_id) BETWEEN 1 AND 64),
    actor_ref varchar(128) COLLATE "C" NOT NULL
        CHECK (octet_length(actor_ref) BETWEEN 1 AND 128),
    reason_code varchar(64) COLLATE "C" NOT NULL
        CHECK (octet_length(reason_code) BETWEEN 1 AND 64),
    plan_digest bytea CHECK (octet_length(plan_digest) = 32),
    batch_bound integer CHECK (batch_bound BETWEEN 1 AND 1000),
    deleted_flow_decisions bigint NOT NULL DEFAULT 0
        CHECK (deleted_flow_decisions >= 0),
    deleted_recovery_decisions bigint NOT NULL DEFAULT 0
        CHECK (deleted_recovery_decisions >= 0),
    deleted_operator_requests bigint NOT NULL DEFAULT 0
        CHECK (deleted_operator_requests >= 0),
    deleted_step_partitions bigint NOT NULL DEFAULT 0
        CHECK (deleted_step_partitions >= 0),
    deleted_step_executions bigint NOT NULL DEFAULT 0
        CHECK (deleted_step_executions >= 0),
    deleted_job_executions bigint NOT NULL DEFAULT 0
        CHECK (deleted_job_executions >= 0),
    deleted_job_instances bigint NOT NULL DEFAULT 0
        CHECK (deleted_job_instances >= 0),
    outcome_class varchar(16) COLLATE "C" NOT NULL
        CHECK (outcome_class IN ('APPLIED', 'REJECTED')),
    applied_at timestamptz NOT NULL,
    CONSTRAINT ob_retention_action_identity_unique
        UNIQUE (action, operation_id),
    CONSTRAINT ob_retention_action_purge_shape
        CHECK (
            (
                action = 'APPLY_PURGE'
                AND plan_digest IS NOT NULL
                AND batch_bound IS NOT NULL
            )
            OR (
                action <> 'APPLY_PURGE'
                AND plan_digest IS NULL
                AND batch_bound IS NULL
            )
        )
);

CREATE INDEX ob_retention_action_instance
    ON ob_retention_action (job_instance_id, id);

CREATE TABLE ob_step_partition (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY CHECK (id > 0),
    step_execution_id bigint NOT NULL
        REFERENCES ob_step_execution (id) ON DELETE RESTRICT,
    worker_step_execution_id bigint
        REFERENCES ob_step_execution (id) ON DELETE RESTRICT,
    partition_key varchar(128) COLLATE "C" NOT NULL
        CHECK (octet_length(partition_key) BETWEEN 1 AND 128),
    partition_ordinal integer NOT NULL CHECK (partition_ordinal > 0),
    status varchar(16) COLLATE "C" NOT NULL
        CHECK (status IN (
            'STARTING', 'STARTED', 'STOPPING', 'STOPPED', 'FAILED',
            'COMPLETED', 'ABANDONED', 'UNKNOWN'
        )),
    exit_code varchar(64) COLLATE "C"
        CHECK (octet_length(exit_code) BETWEEN 1 AND 64),
    read_count bigint NOT NULL DEFAULT 0 CHECK (read_count >= 0),
    processed_count bigint NOT NULL DEFAULT 0 CHECK (processed_count >= 0),
    write_count bigint NOT NULL DEFAULT 0 CHECK (write_count >= 0),
    filter_count bigint NOT NULL DEFAULT 0 CHECK (filter_count >= 0),
    commit_count bigint NOT NULL DEFAULT 0 CHECK (commit_count >= 0),
    rollback_count bigint NOT NULL DEFAULT 0 CHECK (rollback_count >= 0),
    context_format smallint NOT NULL CHECK (context_format > 0),
    context_schema varchar(128) COLLATE "C" NOT NULL
        CHECK (octet_length(context_schema) BETWEEN 1 AND 128),
    context_schema_version integer NOT NULL CHECK (context_schema_version > 0),
    context_payload jsonb NOT NULL
        CHECK (jsonb_typeof(context_payload) = 'object')
        CHECK (pg_column_size(context_payload) <= 4096),
    context_checksum bytea NOT NULL CHECK (octet_length(context_checksum) = 32),
    version bigint NOT NULL DEFAULT 0 CHECK (version >= 0),
    CONSTRAINT ob_step_partition_key_unique
        UNIQUE (step_execution_id, partition_key),
    CONSTRAINT ob_step_partition_ordinal_unique
        UNIQUE (step_execution_id, partition_ordinal)
);

CREATE INDEX ob_step_partition_parent_identity
    ON ob_step_partition (step_execution_id, id);

CREATE INDEX ob_job_instance_name_identity
    ON ob_job_instance (job_name, id DESC);

CREATE INDEX ob_step_execution_execution_identity
    ON ob_step_execution (job_execution_id, id);

CREATE INDEX ob_recovery_decision_execution_identity
    ON ob_recovery_decision (job_execution_id, id);

UPDATE ob_schema_version
    SET version = 3, installed_at = CURRENT_TIMESTAMP
    WHERE singleton;
