SET LOCAL search_path TO oxide_batch, pg_catalog;

DO $$
BEGIN
    IF (SELECT version FROM ob_schema_version WHERE singleton) <> 3 THEN
        RAISE EXCEPTION 'oxide_batch schema version 3 is required before schema 4';
    END IF;
END
$$;

CREATE TABLE ob_component_state (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY CHECK (id > 0),
    step_execution_id bigint NOT NULL
        REFERENCES ob_step_execution (id) ON DELETE RESTRICT,
    namespace varchar(128) COLLATE "C" NOT NULL
        CHECK (octet_length(namespace) BETWEEN 1 AND 128),
    schema_id varchar(128) COLLATE "C" NOT NULL
        CHECK (octet_length(schema_id) BETWEEN 1 AND 128),
    schema_version integer NOT NULL CHECK (schema_version > 0),
    codec_id varchar(128) COLLATE "C" NOT NULL
        CHECK (octet_length(codec_id) BETWEEN 1 AND 128),
    codec_version integer NOT NULL CHECK (codec_version > 0),
    checksum_algorithm smallint NOT NULL CHECK (checksum_algorithm > 0),
    checksum_algorithm_version smallint NOT NULL CHECK (checksum_algorithm_version > 0),
    checksum bytea NOT NULL CHECK (octet_length(checksum) = 32),
    payload_kind varchar(16) COLLATE "C" NOT NULL
        CHECK (payload_kind IN ('INLINE', 'EXTERNAL')),
    -- Stored as the exact codec-produced bytes (not `jsonb`): a `jsonb`
    -- round-trip through Postgres's own decomposed binary representation
    -- does not guarantee reproducing the source whitespace/key-order bytes
    -- the envelope checksum was computed over, so `jsonb` here would let a
    -- validly-committed envelope fail checksum verification after reload.
    -- The JSON-object-shape check still runs, over a UTF-8/JSON-parse of the
    -- stored bytes, without altering what is stored or checksummed.
    payload bytea
        CHECK (payload IS NULL OR octet_length(payload) BETWEEN 1 AND 1048576)
        CHECK (
            payload IS NULL
            OR jsonb_typeof(convert_from(payload, 'UTF8')::jsonb) = 'object'
        ),
    external_content_id bytea
        CHECK (external_content_id IS NULL OR octet_length(external_content_id) = 32),
    external_encoded_len bigint
        CHECK (external_encoded_len IS NULL OR external_encoded_len >= 0),
    version bigint NOT NULL DEFAULT 0 CHECK (version >= 0),
    updated_at timestamptz NOT NULL,
    CONSTRAINT ob_component_state_namespace_unique
        UNIQUE (step_execution_id, namespace),
    CONSTRAINT ob_component_state_payload_shape
        CHECK (
            (payload_kind = 'INLINE' AND payload IS NOT NULL
                AND external_content_id IS NULL AND external_encoded_len IS NULL)
            OR (payload_kind = 'EXTERNAL' AND payload IS NULL
                AND external_content_id IS NOT NULL AND external_encoded_len IS NOT NULL)
        )
);

CREATE INDEX ob_component_state_step_identity
    ON ob_component_state (step_execution_id, namespace);

UPDATE ob_schema_version
    SET version = 4, installed_at = CURRENT_TIMESTAMP
    WHERE singleton;
