SET LOCAL search_path TO oxide_batch, pg_catalog;

DO $$
BEGIN
    IF (SELECT version FROM ob_schema_version WHERE singleton) <> 4 THEN
        RAISE EXCEPTION 'oxide_batch schema version 4 is required before schema 5';
    END IF;
END
$$;

ALTER TABLE ob_flow_decision
    DROP CONSTRAINT ob_flow_decision_transition_kind_check;

ALTER TABLE ob_flow_decision
    ADD CONSTRAINT ob_flow_decision_transition_kind_check
        CHECK (transition_kind IN (
            'STEP_EXIT', 'DECIDER', 'COMPLETED_STEP_REUSE', 'SPLIT_AGGREGATE', 'NESTED_JOB_EXIT'
        ));

CREATE TABLE ob_nested_job_link (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY CHECK (id > 0),
    parent_job_instance_id bigint NOT NULL
        REFERENCES ob_job_instance (id) ON DELETE RESTRICT,
    parent_job_execution_id bigint NOT NULL
        REFERENCES ob_job_execution (id) ON DELETE CASCADE,
    node_id varchar(128) COLLATE "C" NOT NULL
        CHECK (octet_length(node_id) BETWEEN 1 AND 128),
    child_definition_id bigint NOT NULL
        REFERENCES ob_job_definition (id) ON DELETE RESTRICT,
    child_job_instance_id bigint NOT NULL
        REFERENCES ob_job_instance (id) ON DELETE RESTRICT,
    child_job_execution_id bigint NOT NULL
        REFERENCES ob_job_execution (id) ON DELETE RESTRICT,
    linked_at timestamptz NOT NULL,
    terminal_status varchar(16) COLLATE "C"
        CHECK (terminal_status IN ('COMPLETED', 'FAILED', 'STOPPED')),
    terminal_exit_code varchar(64) COLLATE "C"
        CHECK (terminal_exit_code IS NULL OR octet_length(terminal_exit_code) BETWEEN 1 AND 64),
    terminal_observed_at timestamptz,
    CONSTRAINT ob_nested_job_link_parent_node_unique
        UNIQUE (parent_job_execution_id, node_id),
    CONSTRAINT ob_nested_job_link_terminal_shape
        CHECK (
            (terminal_status IS NULL AND terminal_exit_code IS NULL
                AND terminal_observed_at IS NULL)
            OR (terminal_status IS NOT NULL AND terminal_exit_code IS NOT NULL
                AND terminal_observed_at IS NOT NULL)
        )
);

CREATE INDEX ob_nested_job_link_parent_lineage
    ON ob_nested_job_link (parent_job_instance_id, node_id, parent_job_execution_id DESC);
CREATE INDEX ob_nested_job_link_child_execution
    ON ob_nested_job_link (child_job_execution_id);

UPDATE ob_schema_version
    SET version = 5, installed_at = CURRENT_TIMESTAMP
    WHERE singleton;
