SET LOCAL search_path TO oxide_batch, pg_catalog;

DO $$
BEGIN
    IF (SELECT version FROM ob_schema_version WHERE singleton) <> 5 THEN
        RAISE EXCEPTION 'oxide_batch schema version 5 is required before schema 6';
    END IF;
END
$$;

CREATE TABLE ob_scope_resolution_provenance (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY CHECK (id > 0),
    owner_job_execution_id bigint NOT NULL
        REFERENCES ob_job_execution (id) ON DELETE CASCADE,
    owner_step_execution_id bigint
        REFERENCES ob_step_execution (id) ON DELETE CASCADE,
    scope_kind varchar(8) COLLATE "C" NOT NULL
        CHECK (scope_kind IN ('job', 'step')),
    component_id varchar(128) COLLATE "C" NOT NULL
        CHECK (octet_length(component_id) BETWEEN 1 AND 128),
    input_name varchar(128) COLLATE "C" NOT NULL
        CHECK (octet_length(input_name) BETWEEN 1 AND 128),
    source_kind varchar(24) COLLATE "C" NOT NULL
        CHECK (source_kind IN ('job_parameter', 'job_context', 'step_context', 'framework')),
    source_parameter_name varchar(128) COLLATE "C"
        CHECK (
            source_parameter_name IS NULL
            OR octet_length(source_parameter_name) BETWEEN 1 AND 128
        ),
    source_node_id varchar(128) COLLATE "C"
        CHECK (source_node_id IS NULL OR octet_length(source_node_id) BETWEEN 1 AND 128),
    source_framework_field varchar(64) COLLATE "C"
        CHECK (
            source_framework_field IS NULL
            OR source_framework_field IN (
                'job_instance_id',
                'job_execution_id',
                'step_execution_id',
                'attempt',
                'definition_revision',
                'definition_fingerprint',
                'logical_node_id',
                'step_name'
            )
        ),
    source_job_execution_id bigint
        REFERENCES ob_job_execution (id) ON DELETE RESTRICT,
    source_step_execution_id bigint
        REFERENCES ob_step_execution (id) ON DELETE RESTRICT,
    source_execution_version bigint
        CHECK (source_execution_version IS NULL OR source_execution_version >= 0),
    source_schema varchar(128) COLLATE "C"
        CHECK (source_schema IS NULL OR octet_length(source_schema) BETWEEN 1 AND 128),
    source_schema_version integer
        CHECK (source_schema_version IS NULL OR source_schema_version > 0),
    source_path jsonb
        CHECK (
            source_path IS NULL
            OR (
                jsonb_typeof(source_path) = 'array'
                AND jsonb_array_length(source_path) BETWEEN 1 AND 32
                AND pg_column_size(source_path) <= 4096
            )
        ),
    CONSTRAINT ob_scope_resolution_owner_shape
        CHECK (
            (scope_kind = 'job' AND owner_step_execution_id IS NULL)
            OR (scope_kind = 'step' AND owner_step_execution_id IS NOT NULL)
        ),
    CONSTRAINT ob_scope_resolution_source_shape
        CHECK (
            (
                source_kind = 'job_parameter'
                AND source_parameter_name IS NOT NULL
                AND source_job_execution_id IS NOT NULL
                AND source_node_id IS NULL
                AND source_framework_field IS NULL
                AND source_step_execution_id IS NULL
                AND source_execution_version IS NULL
                AND source_schema IS NULL
                AND source_schema_version IS NULL
                AND source_path IS NULL
            )
            OR (
                source_kind = 'job_context'
                AND source_parameter_name IS NULL
                AND source_job_execution_id IS NOT NULL
                AND source_node_id IS NULL
                AND source_framework_field IS NULL
                AND source_step_execution_id IS NULL
                AND source_execution_version IS NOT NULL
                AND source_schema IS NOT NULL
                AND source_schema_version IS NOT NULL
                AND source_path IS NOT NULL
            )
            OR (
                source_kind = 'step_context'
                AND source_parameter_name IS NULL
                AND source_job_execution_id IS NULL
                AND source_node_id IS NOT NULL
                AND source_framework_field IS NULL
                AND (
                    (source_step_execution_id IS NULL AND source_execution_version IS NULL)
                    OR (
                        source_step_execution_id IS NOT NULL
                        AND source_execution_version IS NOT NULL
                    )
                )
                AND source_schema IS NOT NULL
                AND source_schema_version IS NOT NULL
                AND source_path IS NOT NULL
            )
            OR (
                source_kind = 'framework'
                AND source_parameter_name IS NULL
                AND source_job_execution_id IS NOT NULL
                AND source_node_id IS NULL
                AND source_framework_field IS NOT NULL
                AND source_execution_version IS NULL
                AND source_schema IS NULL
                AND source_schema_version IS NULL
                AND source_path IS NULL
            )
        )
);

CREATE UNIQUE INDEX ob_scope_resolution_job_input
    ON ob_scope_resolution_provenance
        (owner_job_execution_id, component_id, input_name)
    WHERE scope_kind = 'job';

CREATE UNIQUE INDEX ob_scope_resolution_step_input
    ON ob_scope_resolution_provenance
        (owner_job_execution_id, owner_step_execution_id, component_id, input_name)
    WHERE scope_kind = 'step';

CREATE INDEX ob_scope_resolution_source_job
    ON ob_scope_resolution_provenance (source_job_execution_id)
    WHERE source_job_execution_id IS NOT NULL;

CREATE INDEX ob_scope_resolution_source_step
    ON ob_scope_resolution_provenance (source_step_execution_id)
    WHERE source_step_execution_id IS NOT NULL;

UPDATE ob_schema_version
    SET version = 6, installed_at = CURRENT_TIMESTAMP
    WHERE singleton;
